# Start Xmodmap
exec xmodmap ~/.Xmodmap &

# Start xkeybinds
exec xbindkeys -f $XDG_CONFIG_HOME/xbindkeys/config &

# Start slstatus
exec slstatus &

# Start nm-applet
exec nm-applet &

# Start dwm
exec dwm
