# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

# Fix scaling for kdenlive
export QT_AUTO_SCREEN_SCALE_FACTOR=0

# Set base directories
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg

# Fix various programs
export HISTFILE="$XDG_STATE_HOME"/bash/history  # Bash
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc  # xinit
alias start="startx $XDG_CONFIG_HOME/X11/xinitrc"

# Set default editor
export EDITOR='nvim'
export VISUAL='nvim'
set -o vi

alias vim='nvim -p'
